# -*- coding: utf-8 -*-
"""Projeto - Etapa 03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLMBWifNDEMBucn2VjMcg5UFWZrApl40

# Etapa 03 - Projeto - Refatoramento da 2
## EDA + Preparação Inicial dos Dados

**Disciplina:** Machine Learning Aplicado  
**Entrega:** notebook preenchido pelo grupo

**Nomes:** Fernando Gomes dos Santos, Izabella Araujo, Luis Felipe, Julia Caramori, Rafaela Virginio

## Identificação do grupo

- **Nome do projeto:** Análise de colheita por condições
- **Dataset utilizado:** https://www.kaggle.com/datasets/firozemaliha/bangladesh-agroclimatic-crop-yield-2000-2024
- **Problema escolhido:** Produção agrícola

## Objetivo

Aplicar no projeto do grupo:

- análise exploratória de dados;
- verificação do target;
- remoção de colunas inadequadas;
- tratamento de valores ausentes;
- análise de variáveis categóricas;
- transformação inicial dos dados;
- preparação da base para modelagem.

> O mais importante não é apenas executar código. O grupo deve **explicar e justificar** as decisões tomadas.

# 1. Importação das bibliotecas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
from kagglehub import KaggleDatasetAdapter
import seaborn as sns
from sklearn.model_selection import train_test_split

"""# 2. Carregamento do dataset

Substitua o nome do arquivo abaixo pelo nome correto do arquivo usado pelo grupo.

"""

# Exemplo:
# df = pd.read_csv("nome_do_arquivo.csv")

df = pd.read_csv("https://raw.githubusercontent.com/6iove/dataset-bangladesh/refs/heads/main/Bangladesh%20Agroclimatic%20Crop%20Yield%20(2000-2024).csv")
df.head()

"""## 2.1 — Descreva o dataset

Responda:

1. O que cada linha representa?
2. Qual é o contexto do dataset?  
3. Qual problema o grupo pretende resolver com esses dados?  

**Resposta do grupo:**

1. Representa a área, local e condições específicas da plantação.  
2. Plantação de arroz boro em Bangladesh.
3. Análise do resultado da colheita em diferentes condições anuais resultando em melhores decisões estratégicas.

# 3. Visão geral dos dados

Observe quantidade de linhas e colunas, nomes, tipos e possíveis problemas iniciais.
"""

df.shape

df.info()

df.columns.tolist()

df.head()

"""## 3.1 — Primeiras observações

Responda:

1. O dataset parece organizado?  
2. Há colunas com nomes confusos?  
3. Há colunas claramente inúteis?  
4. Há colunas com possível *data leakage*?  

**Resposta do grupo:**

1. Sim.
2. Não.
3. Sim.
4. Sim.

# 4. Definição do target

Defina a variável alvo do projeto.

Se o problema for não supervisionado, explique que não há target explícito.
"""

# Exemplo:
# target = "evasao"

target = "Crop yield"

# Execute apenas se houver target supervisionado:
df[target].head()

"""## 4.1 — Justificativa do target

Responda:

1. Qual é o target escolhido?  
2. O que ele representa no mundo real?  
3. Esse target é conhecido antes ou depois do evento?  
4. O problema é de classificação, regressão ou clustering?  

**Resposta do grupo:**

1. A coluna "Crop yield".
2. O que foi colhido.
3. Depois.
4. Regressão.

# 5. Análise do target

Se for classificação, analise a distribuição das classes.  
Se for regressão, analise a distribuição numérica.  
Se for clustering, pule esta etapa e explique por quê.
"""

df[target].describe()

# Para regressão, adapte:

df[target].hist()
plt.title("Distribuição do target", fontsize=14, fontweight="bold")
plt.xlabel("Rendimento (Yield)", fontsize=12)
plt.ylabel("Frequência (Contagem de registros)", fontsize=12)
plt.show()

"""## 5.1 — Interpretação do target

Responda:

1. O target está balanceado?  
2. Existe alguma classe muito dominante?  
3. Isso pode afetar a modelagem?  
4. Qual erro seria mais grave no contexto do projeto?  

**Resposta do grupo:**

1. Não

2. Crop yield

3. Sim

4. Subestimar a produtivade agrícola.

# 6. Remoção de colunas inadequadas

Identifique colunas que não devem entrar no modelo:

- identificadores;
- nomes;
- colunas irrelevantes;
- colunas redundantes;
- colunas com data leakage;
- colunas geradas depois do evento.
"""

# Liste aqui as colunas que o grupo decidiu remover.
# Exemplo:
# colunas_remover = ["id_aluno", "nome_completo"]

colunas_remover = [
    'M.ton',
    'hectares',
]

df_limpo = df.drop(columns=colunas_remover)
df_limpo.head()

g = sns.FacetGrid(df_limpo, col="Division", col_wrap=4, sharex=True)
g.map(sns.histplot, "Crop yield", kde=True, color="seagreen")

g.set_axis_labels("Rendimento (t/ha)", "Frequência")
g.set_titles("{col_name}")
plt.show()

"""## 6.1 — Justificativa das colunas removidas

| Coluna removida | Motivo da remoção |
|---|---|
|  |  |
|  |  |

Classifique o motivo, quando possível: identificador, dado pessoal, irrelevante, leakage, redundante ou inconsistente.

Colunas M.Ton e Hectares

Motivo: Data Leakage já que os dois combinados mostram o resultado final esperado.

# 7. Separação entre X e y

Agora separe:

- `y`: target;
- `X`: features.

Se o projeto for de clustering, defina apenas `X`.
"""

# Para problemas supervisionados:
X = df_limpo.drop(columns=['Crop yield'])
y = df_limpo[target]

X.head()

y.head()

"""## 7.1 — Descrição de X e y

Responda:

1. Quantas features existem em X neste momento?  
2. O target foi removido corretamente de X?  
3. Ainda existe alguma coluna suspeita em X?  

**Resposta do grupo:**

1. 12 Features.

2. Sim.

3. Não.

# 8. Análise de valores ausentes
"""

X.isnull().sum().sort_values(ascending=False)

# Percentual de ausentes por coluna
(X.isnull().mean() * 100).sort_values(ascending=False).round(2)

"""## 8.1 — Interpretação dos valores ausentes

Responda:

1. Quais colunas possuem valores ausentes?  
2. O percentual de ausência é alto ou baixo?  
3. A ausência parece erro de coleta, informação não aplicável ou outro motivo?  
4. Essas colunas são importantes para o problema?  

**Resposta do grupo:**

Como o Dataset já é tratado, não existem valores ausentes.

# 9. Tratamento de valores ausentes

Defina e aplique uma estratégia:

- média: numéricas aproximadamente simétricas;
- mediana: numéricas com outliers ou assimetria;
- moda: categóricas;
- categoria `"Desconhecido"`: quando a ausência também é informação;
- remoção: quando justificável.
"""

X_prep = X.copy()

# EXEMPLOS — adapte ao seu projeto:
# X_prep["coluna_numerica"] = X_prep["coluna_numerica"].fillna(X_prep["coluna_numerica"].median())
# X_prep["coluna_categorica"] = X_prep["coluna_categorica"].fillna("Desconhecido")

# Implemente aqui o tratamento de missing values do grupo.

# Verificação após tratamento
X_prep.isnull().sum().sort_values(ascending=False)

"""## 9.1 — Justificativa do tratamento

| Coluna | Problema encontrado | Tratamento aplicado | Justificativa |
|---|---|---|---|
|  |  |  |  |
|  |  |  |  |


Não houve a necessidade do tratamento, visto que não havia valores nulos.

# 10. Análise de variáveis numéricas

Observe escalas, valores extremos, valores impossíveis e variáveis com pouca variação.
"""

X_prep.describe().T

colunas_numericas = X_prep.select_dtypes(include=["int64", "float64"]).columns.tolist()
colunas_numericas

"""## 10.1 — Interpretação das numéricas

Responda:

1. Há alguma variável numérica com valores estranhos?  
2. Há possível outlier?  
3. Alguma variável tem escala muito diferente das demais?  
4. Alguma variável numérica parece irrelevante?  

**Resposta do grupo:**

1. Não.

2. Não.

3. Não.

4. Não.

# 11. Análise de variáveis categóricas

Identifique colunas categóricas e observe quantidade de categorias, categorias raras e possíveis inconsistências.
"""

colunas_categoricas = X_prep.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
colunas_categoricas

for col in colunas_categoricas:
    print("\nCOLUNA:", col)
    print(X_prep[col].value_counts(dropna=False).head(20))

"""## 11.1 — Interpretação das categóricas

Responda:

1. Quais colunas categóricas existem?  
2. Alguma tem categorias demais?  
3. Alguma tem categorias raras?  
4. Alguma variável categórica possui ordem real?  
5. Qual técnica de encoding parece adequada?  

**Resposta do grupo:**

1. Name, Division.

2. Não.

3. Não.

4. Não.

5.  Label Encoding.

# 12. Encoding das variáveis categóricas

Para variáveis nominais, uma opção inicial é `pd.get_dummies()`.

Para variáveis ordinais, pode ser necessário mapear manualmente a ordem.
"""

# Exemplo de One-Hot Encoding para categóricas nominais:
X_final = pd.get_dummies(X_prep, drop_first=True)

X_final.head()

X_final.dtypes.value_counts()

"""## 12.1 — Justificativa do encoding

Responda:

1. Qual técnica de encoding foi usada?  
2. Por que essa técnica foi escolhida?  
3. Alguma variável exigiria tratamento ordinal?  
4. O número de colunas aumentou muito? Isso é aceitável?  

**Resposta do grupo:**

1. Label Encoding.

2. Essa técnica utiliza menos mémoria e não cria colunas extras.

3. Não.

4. Não, a tecnica de encoding substitui a coluna por números.

# 13. Checagem final da base preparada

A base final deve estar:

- sem valores ausentes;
- sem colunas textuais não tratadas;
- sem target dentro de X;
- sem colunas com leakage;
- em formato numérico.
"""

X_final.isnull().sum().sum()

X_final.dtypes.value_counts()

X_final.shape

X_final.head()

X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)

print(f"Treino: {X_train.shape[0]} amostras")
print(f"Teste: {X_test.shape[0]} amostras")

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Instanciar o modelo
modelo = RandomForestRegressor(n_estimators=100, random_state=42)

# 2. Treinar (O modelo aprende a relação entre clima/região e colheita)
modelo.fit(X_train, y_train)

# 3. Prever (O modelo tenta adivinhar o resultado do conjunto de teste)
previsoes = modelo.predict(X_test)

plt.figure(figsize=(8, 6))
plt.scatter(y_test, previsoes, alpha=0.5, color='blue')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Linha de perfeição
plt.xlabel("Valor Real (Verdadeiro)")
plt.ylabel("Previsão do Modelo")
plt.title("Comparação: Real vs. Previsto")
plt.show()

"""## 13.1 — Relatório final da preparação

Responda:

1. Quantas linhas e colunas ficaram na base final?  
2. Ainda há valores ausentes?  
3. Ainda há variáveis textuais?  
4. O grupo considera a base pronta para modelagem? Justifique.  

**Resposta do grupo:**

1. 5 linhas e 16 colunas.

2. Não.

3. Sim (somente os nomes das cidades).

4. O DataSet não apresentou necessidade de tratamento, a base já está pronta para modelagem.

# 14. Resumo das decisões tomadas

| Etapa | Decisão tomada | Justificativa |
|---|---|---|
| Target |  |  |
| Colunas removidas |  |  |
| Missing values |  |  |
| Categóricas |  |  |
| Encoding |  |  |
| Base final |  |  |

# 15. Reflexão final

Responda:

1. Qual foi a decisão mais difícil da preparação dos dados?  
2. Qual variável gerou mais dúvida?  
3. O grupo identificou algum risco de leakage?  
4. O que ainda precisa ser melhorado antes da modelagem?  
5. O que o grupo aprendeu sobre preparação de dados?  

**Resposta do grupo:**

1. Verificar o balanceamento do target.
2. A Variavel All Sky Surface total PAR.
3. Sim, e foram removidos.
4. Nada pela análise atual.
5. Aprendemos ver o balanceamento do target e a remoção de colunas.

# Parte 3 do projeto, divisão, treinamento e validação

## 1. Importação das bibliotecas
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
import numpy as np
import joblib

"""## 2. Divisão treino/teste e treinamento"""

# Usando X_final (16 features) e y (Crop yield) da Etapa 2
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)

# Inicializando e treinando o modelo escolhido
modelo = RandomForestRegressor(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

# Predição no conjunto de teste
y_pred = modelo.predict(X_test)

"""## 3. Avaliação do modelo"""

print("MAE: ", mean_absolute_error(y_test, y_pred))
print("MSE: ", mean_squared_error(y_test, y_pred))
print("RMSE: ", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2: ", r2_score(y_test, y_pred))

"""### 3.1. Cross-validation"""

# Para regressão — use scoring="r2"
scores = cross_val_score(modelo, X_final, y, cv=5, scoring="r2")

print("Scores por fold:", scores)
print("Media: ", scores.mean())
print("Desvio padrao: ", scores.std())

"""## 4. Exportação do modelo"""

joblib.dump(modelo, "dados_fazenda.pkl")

"""### Responda:
1. Os resultados das métricas indicam um bom desempenho? O modelo supera o baseline da
Etapa 1?
2. O resultado do teste e da cross-validation são próximos? O que isso indica?
3. O modelo apresenta sinais de overfitting ou underfitting?
4. O modelo resolve o problema definido na Etapa 1? Quais são suas principais limitações?
5. Qual foi a maior dificuldade na integração entre o modelo e o sistema?
6. O que o grupo faria diferente se tivesse mais tempo?

Respostas do grupo:

1. Sim, as metricas indicam que o modelo aprendeu a relação entre as variaveis climaticas e a produtividade agrícola. Já na comparação entre a baseline feita na Etapa 1 do projeto, atualmente o modelo apresenha um melhor desempenho e maior capacidade preditiva.

2. Sim, Os resultados do teste e da cross-validation foram próximos o que indicou que o modelo obtem uma boa generalização, isso sugere que o desempenho não ocorreu somente em uma divisão em específica dos dados e que o modelo tem tendencia a manter resultados semelhantes aos novos conjuntos de dados.

3. Como os resultados do teste e da validação cruzada foram próximos, o modelo demonstrou equilibrio bem adequado entre o aprendizado e a capacidade de generalização por tanto, não foi encontrado sinais significativos de overfitting ou underfitting.

4. Sim, o modelo é capaz de estimar a produtividade tendo como base as condições climaticas, regionais como havia sido proposto na primeira etapa, mas suas limitações são dependentes da qualidade dos dados utilizados nas metricas e a possibilidade de não capturar os fatores externos que podem influenciar nos resultados.

5. A maior dificuldade foi na preparação dos dados para que tivessem um formato só para o treinamento, garantindo que as variáveis fossem tratadas corretamente e que não houvesse inconsistências entre os dois lados.

6. Poderiamos fazer outros algoritmos de regressão e poderiamos fazer ajustes de hiperparâmetro para melhorar o desempenho e aumentar a precisão das previsões.
"""